FROM openjdk:8-alpine
MAINTAINER openslice.io
COPY target/io.openslice.portal.api-0.0.1-SNAPSHOT.jar /opt/openslice/lib/
ENV SPRING_APPLICATION_JSON='{ \
	"spring.datasource.url": "jdbc:mysql://10.0.2.15/osdb?createDatabaseIfNotExist=true",  \
	"spring.activemq.broker-url": "tcp://10.0.2.15:61616"  }'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/openslice/lib/io.openslice.portal.api-0.0.1-SNAPSHOT.jar"]
EXPOSE 13000